name: io.js cn
description: iojs-cn 组织成立的目的是为了推进 io.js 在中国的普及，并及时同步英文社区的最新资讯
avatar: https://avatars1.githubusercontent.com/u/9950313?v=3&s=200
footer-links:
  github: iojs/iojs-cn
  rss: "on"
  twitter: iojs_cn

disqus:
google_analytics:
url: "http://iojs.github.io/iojs-cn"
baseurl: "/iojs-cn"

excerpt_separator: "<!--more-->"

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: assets/scss
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
    - README.md
